// Code generated by protoc-gen-go.
// source: logic.proto
// DO NOT EDIT!

/*
Package logic is a generated protocol buffer package.

It is generated from these files:
	logic.proto

It has these top-level messages:
	MessageRequest
	ReceiveReply
*/
package logic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageRequest struct {
	MsgType    int32  `protobuf:"varint,1,opt,name=MsgType,json=msgType" json:"MsgType,omitempty"`
	SequenceId string `protobuf:"bytes,2,opt,name=SequenceId,json=sequenceId" json:"SequenceId,omitempty"`
	ConnId     string `protobuf:"bytes,3,opt,name=ConnId,json=connId" json:"ConnId,omitempty"`
	Sender     string `protobuf:"bytes,4,opt,name=Sender,json=sender" json:"Sender,omitempty"`
	Receiver   string `protobuf:"bytes,5,opt,name=Receiver,json=receiver" json:"Receiver,omitempty"`
	Body       string `protobuf:"bytes,6,opt,name=Body,json=body" json:"Body,omitempty"`
}

func (m *MessageRequest) Reset()                    { *m = MessageRequest{} }
func (m *MessageRequest) String() string            { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()               {}
func (*MessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReceiveReply struct {
	Status  bool   `protobuf:"varint,1,opt,name=Status,json=status" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,json=message" json:"Message,omitempty"`
}

func (m *ReceiveReply) Reset()                    { *m = ReceiveReply{} }
func (m *ReceiveReply) String() string            { return proto.CompactTextString(m) }
func (*ReceiveReply) ProtoMessage()               {}
func (*ReceiveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*MessageRequest)(nil), "logic.MessageRequest")
	proto.RegisterType((*ReceiveReply)(nil), "logic.ReceiveReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Logic service

type LogicClient interface {
	ReceiveMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*ReceiveReply, error)
}

type logicClient struct {
	cc *grpc.ClientConn
}

func NewLogicClient(cc *grpc.ClientConn) LogicClient {
	return &logicClient{cc}
}

func (c *logicClient) ReceiveMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*ReceiveReply, error) {
	out := new(ReceiveReply)
	err := grpc.Invoke(ctx, "/logic.Logic/ReceiveMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Logic service

type LogicServer interface {
	ReceiveMessage(context.Context, *MessageRequest) (*ReceiveReply, error)
}

func RegisterLogicServer(s *grpc.Server, srv LogicServer) {
	s.RegisterService(&_Logic_serviceDesc, srv)
}

func _Logic_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logic.Logic/ReceiveMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).ReceiveMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logic.Logic",
	HandlerType: (*LogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _Logic_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x26, 0x9b, 0x38, 0x4a, 0x0f, 0x23, 0xca, 0xd2, 0x83, 0x94, 0x9c, 0x7a, 0xea,
	0x41, 0xef, 0x22, 0x7a, 0x90, 0x82, 0xbd, 0x6c, 0xfd, 0x03, 0x6d, 0x76, 0x08, 0x85, 0x36, 0x1b,
	0x33, 0x1b, 0x61, 0xff, 0x92, 0xbf, 0x52, 0x32, 0xbb, 0x88, 0x1e, 0xbf, 0x37, 0x8f, 0x99, 0x79,
	0x0f, 0xae, 0x8e, 0xae, 0x3d, 0x34, 0xab, 0x7e, 0x70, 0xde, 0x61, 0x21, 0x50, 0x7f, 0x67, 0x30,
	0xdb, 0x10, 0xf3, 0xae, 0x25, 0x43, 0x9f, 0x23, 0xb1, 0x47, 0x0d, 0xe5, 0x86, 0xdb, 0x8f, 0xd0,
	0x93, 0xce, 0x16, 0xd9, 0xb2, 0x30, 0xe5, 0x29, 0x22, 0xde, 0x03, 0x6c, 0x27, 0x53, 0xd7, 0xd0,
	0xda, 0xea, 0xf3, 0x45, 0xb6, 0xbc, 0x34, 0xc0, 0xbf, 0x0a, 0xde, 0x81, 0x7a, 0x75, 0x5d, 0xb7,
	0xb6, 0xfa, 0x42, 0x66, 0xaa, 0x11, 0x9a, 0xf4, 0x2d, 0x75, 0x96, 0x06, 0x9d, 0x47, 0x9d, 0x85,
	0x70, 0x0e, 0x95, 0xa1, 0x86, 0x0e, 0x5f, 0x34, 0xe8, 0x42, 0x26, 0xd5, 0x90, 0x18, 0x11, 0xf2,
	0x17, 0x67, 0x83, 0x56, 0xa2, 0xe7, 0x7b, 0x67, 0x43, 0xfd, 0x0c, 0xd7, 0xc9, 0x6f, 0xa8, 0x3f,
	0x06, 0xd9, 0xeb, 0x77, 0x7e, 0x64, 0x79, 0xb4, 0x32, 0x8a, 0x85, 0x24, 0x41, 0xcc, 0x94, 0x9e,
	0x2c, 0x4f, 0x11, 0x1f, 0xde, 0xa0, 0x78, 0x9f, 0x72, 0xe3, 0x13, 0xcc, 0xd2, 0xaa, 0xe4, 0xc4,
	0xdb, 0x55, 0xac, 0xe7, 0x7f, 0x1b, 0xf3, 0x9b, 0x24, 0xff, 0x3d, 0x5c, 0x9f, 0xed, 0x95, 0xb4,
	0xf8, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x03, 0xd1, 0xbb, 0x99, 0x54, 0x01, 0x00, 0x00,
}
